export interface PaletteColor {
  name: string;
  hex: string;
}

export const PALETTE: PaletteColor[] = [
  { name: 'Pomegranate',   hex: '#c0392b' },
  { name: 'Pumpkin',       hex: '#d35400' },
  { name: 'Tangerine',     hex: '#e67e22' },
  { name: 'Sunflower',     hex: '#f1c40f' },
  { name: 'Citrus',        hex: '#a8b820' },
  { name: 'Emerald',       hex: '#27ae60' },
  { name: 'Nephritis',     hex: '#1e8449' },
  { name: 'Turquoise',     hex: '#1abc9c' },
  { name: 'Green Sea',     hex: '#16a085' },
  { name: 'Peter River',   hex: '#3498db' },
  { name: 'Belize Hole',   hex: '#2980b9' },
  { name: 'Amethyst',      hex: '#9b59b6' },
  { name: 'Wisteria',      hex: '#8e44ad' },
  { name: 'Wet Asphalt',   hex: '#34495e' },
  { name: 'Midnight Blue', hex: '#2c3e50' },
  { name: 'Alizarin',      hex: '#e74c3c' },
  { name: 'Concrete',      hex: '#95a5a6' },
  { name: 'Dark Red',      hex: '#922b21' },
  { name: 'Dark Pumpkin',  hex: '#a04000' },
  { name: 'Dark Teal',     hex: '#117a65' },
  { name: 'Dark Navy',     hex: '#154360' },
  { name: 'Dark Violet',   hex: '#512e5f' },
  { name: 'Espresso',      hex: '#6d4c41' },
  { name: 'Steel Blue',    hex: '#4682b4' },
  { name: 'Sea Green',     hex: '#2e8b57' },
  { name: 'Coral',         hex: '#e8735a' },
  { name: 'Orchid',        hex: '#b85cc8' },
  { name: 'Sky Blue',      hex: '#5b9bd5' },
  { name: 'Sage',          hex: '#6b8e6b' },
  { name: 'Dusty Rose',    hex: '#b87070' },
  { name: 'Cobalt',        hex: '#3d4eb8' },
  { name: 'Olive',         hex: '#808000' },
  { name: 'Maroon',        hex: '#800000' },
  { name: 'Pine',          hex: '#2d5a27' },
  { name: 'Ocean',         hex: '#006994' },
  { name: 'Lavender',      hex: '#6a5acd' },
];
